package rules

import com.javainuse.model.Product

rule "Offer for Diamond"
	when 
	   productObject: Product(typekwando=="hehehaha")
	then
	   productObject.setDiscount(67);  
	   end 
rule "Offer for Gold"
	when 
		productObject: Product(typekwando=="mutata")
	then
		productObject.setDiscount(553);
	end
rule "Offer for parnali"
	when 
		productObject: Product(typekwando=="parnali")
	then
		productObject.setDiscount(98);
		System.out.println(drools.getRule().getName());
	end
rule "Offer for parnali8"
	when 
		productObject: Product(typekwando=="parnali")
	then
		productObject.setDiscount(986);
		System.out.println(drools.getRule().getName());
	end	